/** First two digits of SG postal code → planning area / town (approximate). */
const SECTOR_TOWN: Record<string, string> = {
  "01": "Downtown Core",
  "02": "Tanjong Pagar",
  "03": "Central",
  "04": "Harbourfront",
  "05": "Outram",
  "06": "Downtown Core",
  "07": "Rochor",
  "08": "Rochor",
  "09": "Orchard",
  "10": "Bukit Timah",
  "11": "Bukit Merah",
  "12": "Bukit Merah",
  "13": "Bukit Merah",
  "14": "Kallang",
  "15": "Marine Parade",
  "16": "Bedok",
  "17": "Changi",
  "18": "Tampines",
  "19": "Hougang",
  "20": "Hougang",
  "21": "Hougang",
  "22": "Punggol",
  "23": "Bukit Timah",
  "24": "Bukit Timah",
  "25": "Woodlands",
  "26": "Springleaf",
  "27": "Yishun",
  "28": "Yishun",
  "29": "Seletar",
  "30": "Ang Mo Kio",
  "31": "Ang Mo Kio",
  "32": "Ang Mo Kio",
  "33": "Serangoon",
  "34": "Serangoon",
  "35": "Serangoon",
  "36": "Serangoon",
  "37": "Serangoon",
  "38": "Hougang",
  "39": "Hougang",
  "40": "Serangoon",
  "41": "Serangoon",
  "42": "Serangoon",
  "43": "Punggol",
  "44": "Punggol",
  "45": "Punggol",
  "46": "Punggol",
  "47": "Punggol",
  "48": "Tampines",
  "49": "Changi",
  "50": "Bedok",
  "51": "Bedok",
  "52": "Bedok",
  "53": "Bedok",
  "54": "Bedok",
  "55": "Geylang",
  "56": "Toa Payoh",
  "57": "Toa Payoh",
  "58": "Bishan",
  "59": "Bishan",
  "60": "Bukit Batok",
  "61": "Bukit Batok",
  "62": "Bukit Batok",
  "63": "Bukit Batok",
  "64": "Jurong East",
  "65": "Bukit Batok",
  "66": "Bukit Batok",
  "67": "Choa Chu Kang",
  "68": "Choa Chu Kang",
  "69": "Tuas",
  "70": "Lim Chu Kang",
  "71": "Lim Chu Kang",
  "72": "Lim Chu Kang",
  "73": "Choa Chu Kang",
  "74": "Choa Chu Kang",
  "75": "Yishun",
  "76": "Yishun",
  "77": "Yishun",
  "78": "Yishun",
  "79": "Central",
  "80": "Central",
  "81": "Bukit Merah",
  "82": "Bukit Merah",
};

export function postalSector(postalCode: string): string | null {
  const digits = postalCode.replace(/\D/g, "");
  if (digits.length < 2) return null;
  return digits.slice(0, 2);
}

export function townFromPostal(postalCode: string): string {
  const sector = postalSector(postalCode);
  if (!sector) return "Singapore";
  return SECTOR_TOWN[sector] ?? "Singapore";
}
